FROM jupyter/scipy-notebook

WORKDIR workdir
ENV MODEL_DIR=/home/llama2/model
ENV MODEL_FILE_LDA=clf_lda.joblib
ENV MODEL_FILE_NN=clf_nn.joblib

RUN pip install joblib

COPY src/train.csv ./src/train.csv
COPY src/test.csv ./src/test.csv

COPY src/train.py ./src/train.py
COPY src/inference.py ./src/inference.py

RUN python3 src/train.py
